from turtle import clear


print('Hi , this is a small programme which work as a average calculator ')

print(" I am shan , basically a small programmer and a script kiddie 😎")

a = input('enter your first number:')
b = input('enter your second number:')
a = int(a)
b = int(b)
avg = (a+b)/2
print('The desired result is', avg)

print('thanks for using this programme 🤗')

print("thanks 🤗🤗🤗🤗🤗🤗")

